version: '3'

services:

  app:
    container_name: app
    build: .
    links:
      - 'db:db'
    depends_on:
      - 'db'
    ports: 
      - '8080:8080'
    restart: 
      on-failure
  
  db:
    container_name: db
    image: mongo:4.0
    volumes: 
      - ./data-volume:/data/db
    restart: 
      on-failure
  
