version: '3'

services:

  client:
    container_name: client
    build: client/
    depends_on:
      - 'api'
    volumes: 
      - './urls.js:/urls.js'
    restart: 
      on-failure
  
  api:
    container_name: api
    build: api/
    links:
      - 'db:db'
    depends_on:
      - 'db'
    ports: 
      - '8080:8080'
    restart: 
      on-failure
  
  db:
    container_name: db
    image: mongo:4.0
    volumes: 
      - ./data-volume:/data/db
    restart: 
      on-failure
  
