version: '3'

services:

  client:
    container_name: client
    build: client/
    depends_on:
      - 'api'
    ports:
      - '8080:8080'
    restart: 
      on-failure
  
  api:
    container_name: api
    build: api/
    links:
      - 'db:db'
    depends_on:
      - 'db'
    ports: 
      - '7200:7200'
    restart: 
      on-failure
  
  db:
    container_name: db
    image: mongo:4.0
    ports:
      - '27022:27022'
    restart: 
      on-failure
  
