export const ADD_EMPLOYEES = "ADD_EMPLOYEES";

export const SELECT_EMPLOYEE = "SELECT_EMPLOYEE";

export const TOGGLE_MODAL = "CHANGE_MODAL";

export const LOG_ERRORS = "LOG_ERRORS";

export const RESET_FORM = "RESET_FORM";

export const UPDATE_EMPLOYEES = "UPDATE_EMPLOYEES";