export const ADD_EMPLOYEE = "ADD_EMPLOYEE";

export const SELECT_EMPLOYEE = "SELECT_EMPLOYEE";

export const TOGGLE_MODAL = "CHANGE_MODAL";

export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";

export const LOG_ERRORS = "LOG_ERRORS"