export const SET_EMPLOYEES = "SET_EMPLOYEES";
export const SELECT_EMPLOYEE = "SELECT_EMPLOYEE";

export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const CLOSE_ALL_MODALS = "CLOSE_ALL_MODALS";

export const UPDATE_FIELD = "UPDATE_FIELD";
export const UPDATE_FORM = "UPDATE_FORM";
export const VALIDATE_FIELD = "VALIDATE_FIELD";
export const SET_FORM_IS_VALID = "SET_FORM_IS_VALID"
export const RESET_FORM = "RESET_FORM";

